#!/bin/bash
type=`cut -d "_" -f 2 <<< "$0"`
type_upper="$(tr '[:lower:]' '[:upper:]' <<< ${type:0:1})${type:1}"
if [ "$1" = "config" ]; then
  echo "graph_category bitcoin"
  echo "graph_title Bitcoin $type_upper"
  echo "graph_vlabel $type_upper"
  echo "$type.label $type"
else
  bcpath="/usr/local/bin/bitcoin-cli"
  if [ "$type" = "connections" ]; then
    value=`$bcpath getconnectioncount`
  elif [ "$type" = "blocks" ]; then
    value=`$bcpath getblockcount`
  elif [ "$type" = "difficulty" ]; then
    value=`$bcpath getdifficulty`
  elif [ "$type" = "mempoolbytes" ]; then
    value=`$bcpath getmempoolinfo | grep -Po '\"bytes\".*' | grep -Po '[0-9]*'`
  elif [ "$type" = "mempoolcount" ]; then
    value=`$bcpath getmempoolinfo | grep -Po '\"size\".*' | grep -Po '[0-9]*'`
  fi
  echo "$type.value $value"
fi
